///import type { Metadata } from 'next';
//import { globalFont } from '@/config/fonts';
//import './globals.css';

import { auth } from '@/auth.config';
import { redirect } from 'next/navigation';

//const inter = Inter({ subsets: ["latin"] });

/* export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}; */

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const session = await auth();

  if (session?.user) {
    //redirect('/auth/login');
    redirect('/');
  }

  return (
    <>
      <header>LAyout Autenticacion</header>
      <main className="flex justify-center">
        <div className="w-full sm:w-[500px] px-10">{children}</div>
      </main>
      <footer>Pie de pagina</footer>
    </>
  );
}
