import type { Metadata } from 'next';
import { globalFont } from '@/config/fonts';
import './globals.css';
import { Providers } from '@/components';

//const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${globalFont.className} text-sm font-normal `}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
